// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qoffospdwigafqfyqpeg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFvZmZvc3Bkd2lnYWZxZnlxcGVnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzUwOTAwNjEsImV4cCI6MjA1MDY2NjA2MX0.UwKyNv7IK5GLR6bmeePkIMpEOCeuD-Mqk-sb6OEMepY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);